### ISSUE TITLE
Examples: app with several pages

### ISSUE THREAD

**Issue by mckn** [grafana/plugins-examples#3]
### Description
Create a plugin that contains an app with several pages. This should be an example of how to create a basic app without any advance functionality. 

### Tasks
- [ ] Root page with routing
   - [ ] Showcase how create page with tabs.
   - [ ] Showcase how create page without tabs.
   - [ ] Showcase how create full width page.
   - [ ] Showcase how to navigate between pages.
- [ ] Configuration page.
   - [ ] Showcase how to manage secrets e.g. API keys etc.
   - [ ] Showcase how to use the form components.
- [ ] Integration tests that verifies that the features that being used from Grafana plugin API is working as expected.
