### ISSUE TITLE
Examples: panel that visualize time series data

### ISSUE THREAD

**Issue by mckn** [grafana/plugins-examples#4]
### Description
Create a plugin that contains a panel with custom configuration. This should be an example of how to create a basic panel without any advance functionality. 

### Tasks
- [ ] Panel plugin
   - [ ] Showcase how add custom configuration for panel.
   - [ ] Showcase how use custom configuration in panel.
   - [ ] Showcase how to use grafana-ui time series visualization.
   - [ ] Showcase how to update time range for dashboard programmatically from panel.
- [ ] Integration tests that verifies that the features that being used from Grafana plugin API is working as expected.
